# Generated by Django 5.0.7 on 2024-07-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_media_alter_tweet_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='media',
        ),
        migrations.AddField(
            model_name='tweet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.TextField(max_length=280),
        ),
    ]
